# Generated by Django 4.2.1 on 2023-05-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Productos Publicados',
                'verbose_name_plural': 'CondicionesProductos',
                'db_table': 'Producto',
            },
        ),
    ]
