# Generated by Django 4.2.1 on 2023-05-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0002_categoria_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estado del Producto',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ABM.estado'),
            preserve_default=False,
        ),
    ]
