# Generated by Django 4.2.1 on 2023-05-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0003_estado_producto_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id_condicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Condicion venta/trueque del Producto',
                'verbose_name_plural': 'Condiciones',
                'db_table': 'Condicion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.TextField(max_length=1000)),
                ('ciudad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('cp', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('id_usuario', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Usuarios que compran/venden/trocan productos',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_condicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ABM.condicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_vendedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ABM.usuario'),
            preserve_default=False,
        ),
    ]
