# Generated by Django 4.2.1 on 2023-05-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0004_condicion_usuario_producto_id_condicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABM.usuario')),
            ],
            options={
                'verbose_name': 'Datos de la carga de productos',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carrito',
            },
        ),
    ]
