# Generated by Django 4.2.1 on 2023-05-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0005_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABM.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABM.producto')),
            ],
            options={
                'verbose_name': 'Detalle de la carga de productos',
                'verbose_name_plural': 'Detalles_Carrito',
                'db_table': 'CarritoDetalle',
            },
        ),
    ]
