# Generated by Django 4.2.1 on 2023-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0008_remove_usuario_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='Sin Observar', max_length=100),
        ),
    ]
