# Generated by Django 4.2.1 on 2023-05-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0009_pedido_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='observacion',
        ),
    ]
