# Generated by Django 4.2.1 on 2023-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0011_carrito_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='observacion',
        ),
    ]
