# Generated by Django 4.2.1 on 2023-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0013_carrito_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='domicilio_envio',
            field=models.TextField(default='El mismo domicilio del usuario', max_length=1000),
        ),
    ]
