# Generated by Django 4.2.1 on 2023-06-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0015_remove_producto_id_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_comprador',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_comprador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='provincia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='admin123', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=80),
        ),
    ]
